# 1.Perform the following operations on the given matrices:

In [3]:
import numpy as np
A = np.array([[2,-1], [0,3]])     
B=np.array([[1,2],[-3,4]])             # representation of metrices using numpy
print(A) 

print(B)

[[ 2 -1]
 [ 0  3]]
[[ 1  2]
 [-3  4]]


##### a.A+B


In [5]:
sum=A+B
print("sum\n",sum)

sum
 [[ 3  1]
 [-3  7]]


#### b.AB


In [6]:
product = np.dot(A,B)
print("AB\n",product)

AB: 
 [[ 5  0]
 [-9 12]]


#### c.3A-2B

In [8]:
simplify = 3 * A - 2 * B
print("3A-2B\n",simplify)

3A-2B
 [[ 4 -7]
 [ 6  1]]


# 2. Determinants and Inverses  

In [10]:
det_A = np.linalg.det(A)
print("Determinant of A is\n",det_A)

Determinant of A is
 6.0


#### Determine whether A is invertible. If yes, calculate A−1.

In [11]:
a = det_A
if a != 0:
    A_inv = True
    print("Yes the matrix A is invertible")
else:
    A_inv = False
    print("No the matrix A is not invertible")
if A_inv:
    inv_A= np.linalg.inv(A)
    print("Invertible of A is :\n",inv_A)

Yes the matrix A is invertible
Invertible of A is :
 [[0.5        0.16666667]
 [0.         0.33333333]]


# Eigenvalues and Eigenvectors

##### Compute the eigenvalues and eigenvectors of the matrix:

In [13]:
C = np.array([[4, 1], [-2, 1]])
eigenvalues, eigenvectors = np.linalg.eig(C)
print("Eigenvectors of C is\n", eigenvalues)
print("Eigenvectors of C is\n", eigenvectors)

Eigenvectors of C is
 [3. 2.]
Eigenvectors of C is
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


###### 
You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)

car 1:

x1: 4

x2: 1.5

x3: 100

and price: 20

car 2:

x1: 6

x2: 2.0

x3: 150

and price: 30

Then, find the price of a car 3 with features x1: 8

x2: 3.0

x3: 200

price:?

In [14]:
X = np.array([[4, 1.5, 100], [6, 2.0, 150]])
y = np.array([20, 30])
beta = np.linalg.pinv(X.T @ X) @ X.T @ y
car3 = np.array([8, 3.0, 200])
price3 = car3 @ beta
print("The estimated price of car 3:", price3)

The estimated price of car 3: 40.000000000000696
